apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oidc.fullname" . }}
  namespace: {{ include "oidc.namespace" . }}
data:
  traefik.toml: |
    # --------------------- #
    # Static Configuration  #
    # --------------------- #


    [global]
    checkNewVersion = false

    [entryPoints]
    [entryPoints.web]
    address = ":8888"

    [providers]
    [providers.file]
    filename = "/etc/traefik/traefik.toml"
    watch = true

    [log]
    level = "ERROR" # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO

    # --------------------- #
    # Dynamic Configuration #
    # --------------------- #

    [http]
    [http.routers]
    [http.routers.secure]
    entryPoints = ["web"]
    middlewares = ["traefik-forward-auth-secure"]
    service = "secure"
    rule = "Host(`{{ include "oidc.fullname" $ }}-{{ .Chart.Name }}.{{ include "oidc.fullname" $ }}.{{ include "oidc.namespace" $ }}.svc.{{ $.Values.clusterDomain }}`) && PathPrefix(`/PlantaServerAdapter`)"
    [http.routers.webclient]
    entryPoints = ["web"]
    middlewares = ["traefik-forward-auth-webclient"]
    service = "webclient"
    rule = "Host(`{{ include "oidc.fullname" $ }}-{{ .Chart.Name }}.{{ include "oidc.fullname" $ }}.{{ include "oidc.namespace" $ }}.svc.{{ $.Values.clusterDomain }}`)"
    [http.middlewares]
    [http.middlewares.traefik-forward-auth-secure.forwardauth]
    address = "http://{{ include "oidc.fullname" $ }}-forward-auth-secure.{{ include "oidc.fullname" $ }}.{{ include "oidc.namespace" $ }}.svc.{{ $.Values.clusterDomain }}:4181"
    authResponseHeaders = ["X-Forwarded-User"]
    [http.middlewares.traefik-forward-auth-webclient.forwardauth]
    address = "http://{{ include "oidc.fullname" $ }}-forward-auth-webclient.{{ include "oidc.fullname" $ }}.{{ include "oidc.namespace" $ }}.svc.{{ $.Values.clusterDomain }}:4181"
    authResponseHeaders = ["X-Forwarded-User"]
    [http.services]
    [http.services.secure.loadBalancer]
    [[http.services.secure.loadBalancer.servers]]
    url = "{{ .Values.oidcSettings.secure.url }}"
    [http.services.webclient.loadBalancer]
    [[http.services.webclient.loadBalancer.servers]]
    url = "{{ .Values.oidcSettings.webclient.url }}"