apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc.fullname" . }}
  namespace: {{ include "oidc.namespace" . }}
  labels:
    {{- include "oidc.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oidc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oidc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oidc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: traefik-conf
          configMap:
            name: {{ include "oidc.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: traefik-conf
              mountPath: /etc/traefik/traefik.toml
              subPath: traefik.toml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: forward-auth-webclient
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.forwardAuthImage.repository }}:{{ .Values.forwardAuthImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: INSECURE_COOKIE
              value: {{ .Values.oidcSettings.insecureCookie | quote }}
            - name: DEFAULT_PROVIDER
              value: oidc
            - name: LIFETIME
              value: {{ .Values.oidcSettings.lifetime | quote }}
            - name: URL_PATH
              value: {{ .Values.oidcSettings.webclient.path | quote }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidcSettings.secretName }}
                  key: clientSecret
            - name: PORT
              value: "4181"
            - name: PROVIDERS_OIDC_ISSUER_URL
              value: {{ .Values.oidcSettings.issuerURL | quote }}
            - name: PROVIDERS_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidcSettings.secretName }}
                  key: clientID
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidcSettings.secretName }}
                  key: clientSecret
          ports:
            - name: webclient-http
              containerPort: 4181
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 4181
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 4181
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 4181
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: forward-auth-secure
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.forwardAuthImage.repository }}:{{ .Values.forwardAuthImage.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: INSECURE_COOKIE
              value: {{ .Values.oidcSettings.insecureCookie | quote }}
            - name: DEFAULT_PROVIDER
              value: oidc
            - name: LIFETIME
              value: {{ .Values.oidcSettings.lifetime | quote }}
            - name: URL_PATH
              value: {{ .Values.oidcSettings.secure.path | quote }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidcSettings.secretName }}
                  key: clientSecret
            - name: PORT
              value: "4182"
            - name: PROVIDERS_OIDC_ISSUER_URL
              value: {{ .Values.oidcSettings.issuerURL | quote }}
            - name: PROVIDERS_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidcSettings.secretName }}
                  key: clientID
            - name: PROVIDERS_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidcSettings.secretName }}
                  key: clientSecret
          ports:
            - name: secure-http
              containerPort: 4182
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 4182
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 4182
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 4182
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
