apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "oidc.fullname" . }}
  namespace: {{ include "oidc.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "oidc.serviceAccountName" . }} # "name" is case sensitive
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: {{ include "oidc.fullname" . }} # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
