apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "oidc.fullname" . }}
  namespace: {{ include "oidc.namespace" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
