apiVersion: v1
kind: Service
metadata:
  name: {{ include "oidc.fullname" . }}
  namespace: {{ include "oidc.namespace" . }}
  labels:
    {{- include "oidc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "oidc.selectorLabels" . | nindent 4 }}
